apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk-main-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk-main
  template:
    metadata:
      labels:
        app: dwk-main
      containers:
#        - name: dwk-timestamp-creator
#          image: janzu/dwk-timestamp-creator:latest
        - name: dwk-timestamp-http
          image: janzu/dwk-timestamp-http:latest

