apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk-main-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk-main
  template:
    metadata:
      labels:
        app: dwk-main
    spec:
      volumes:
        - name: dwk-main-storage
          emptyDir: {}
      containers:
        - name: dwk-timestamp-creator
          image: janzu/dwk-timestamp-creator:latest
          volumeMounts:
            - name: dwk-main-storage
              mountPath: /usr/src/app/files
        - name: dwk-timestamp-http
          image: janzu/dwk-timestamp-http:latest
          volumeMounts:
            - name: dwk-main-storage
              mountPath: /usr/src/app/files

