apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: randomstring-ingress
  annotations:
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: randomstring-svc
              servicePort: 2345
          - path: /pingpong
            backend:
              serviceName: dwk-pingpong-svc
              servicePort: 2346