apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk-pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk-pingpong
  template:
    metadata:
      labels:
        app: dwk-pingpong
    spec:
      volumes:
        - name: dwk-pv
          persistentVolumeClaim:
            claimName: dwk-pingpong-claim
      containers:
        - name: dwk-pingpong
          image: janzu/dwk-pingpong:latest